name: Build settings plugin
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Build
        run: |
          mkdir sm
          unzip -q settings-menu-project.zip -d sm
          mvn -B -q -f sm/pom.xml package
      - uses: actions/upload-artifact@v4
        with:
          name: SettingsMenu-jar
          path: sm/target/SettingsMenu.jar

