name: Build plugin
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: unzip -q DonutRTP-source.zip
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven
      - run: mvn -B -f DonutRTP/pom.xml package
      - uses: actions/upload-artifact@v4
        with:
          name: DonutRTP
          path: DonutRTP/target/DonutRTP.jar
